T_END = 100000
T_TUNE = 0.5
#T_MAX = 2

CONNECTION_SPEED = 10 #pakages per time tick

ADDITION = 5 #correction for new arrivals(in calls)
PROBABILITY_OF_SMALL_GROUP = 0.7
SIZE_OF_SMALL_GROUP = 1
SIZE_OF_BIG_GROUP = 5
T_SERVE = 1/CONNECTION_SPEED

NUMBER_OF_THREADS = 3
#ARRAY_OF_LAMBDAS = [3,5,1]